# Generated by Django 2.2 on 2019-05-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
